import test from 'node:test'
import assert from 'node:assert/strict'
import {latestPayload,dayRecords,trendRecords,monthRecords,handleSimulationRequest} from '../server/simulation.js'
import {normalizePayload,ANALOG,DIGITAL} from '../src/digital-twin/telemetry.js'
import {buildCoverage} from '../src/data/waterRecords.js'
import {buildTrend,TREND_CATEGORIES} from '../src/data/trendData.js'
const NOW=Date.parse('2026-10-04T15:45:00+08:00')
test('cloud telemetry is bounded, dynamic and ties lamps to the measured level',()=>{const first=latestPayload(NOW),next=latestPayload(NOW+3000);assert.equal(first.source,'cloud-simulation');assert.equal(first.latest_data.length,ANALOG.length);assert.equal(first.check_data.length,DIGITAL.length);const a=normalizePayload(first).values,b=normalizePayload(next).values;assert.notEqual(a[115],b[115]);assert.equal(a[138],Number(a[115]>=4.3));assert.equal(a[139],Number(a[115]>=3.3));assert.equal(a[158],Number(a[115]>=2.3));assert.equal(a[140],Number(a[115]>=1.3));assert.ok(Object.values(a).every(Number.isFinite));assert.ok(b[109]>=a[109])})
test('history, trend and report derive from the same stable samples',()=>{const date='2025-05-31',rows=dayRecords(date,NOW),trend=trendRecords(date,'累計流量',NOW);assert.deepEqual(rows,dayRecords(date,NOW));assert.equal(buildTrend(trend,TREND_CATEGORIES[1],date).series[0].stats.count,24);assert.equal(trend.at(-1).value,rows.findLast(r=>r.element_no===trend.at(-1).element_no).value);const month=monthRecords('2025','05',NOW);assert.ok(month.length>9000);const series=rows.filter(r=>r.element_no==='109');assert.ok(series.every((r,i)=>!i||Number(r.value)>=Number(series[i-1].value)));assert.ok(buildCoverage(rows,date,new Date(NOW)).integrity<=100)})
test('future samples are omitted and invalid API input is rejected',async()=>{const today=dayRecords('2026-10-04',NOW);assert.ok(today.every(r=>Number(r.time.slice(0,2))<=15));assert.throws(()=>dayRecords('2026-02-30',NOW));assert.throws(()=>monthRecords('2026','13',NOW));let response=await handleSimulationRequest(new Request('https://example.org/api/data_third.php'), 'data_third.php',NOW);assert.equal(response.status,200);assert.equal(response.headers.get('X-Aquatic-Data-Source'),'cloud-simulation');response=await handleSimulationRequest(new Request('https://example.org/api/alert_3.php',{method:'POST',body:'{}'}),'alert_3.php',NOW);assert.equal(response.status,400);response=await handleSimulationRequest(new Request('https://example.org/api/no'),'no',NOW);assert.equal(response.status,404)})
